{
 "title": "F1 Analytics",
 "time": { "from": "2020-08-09T13:13:17.118Z", "to": "2020-08-09T14:31:56.727Z" },
 "templating": {
  "list": [
   {
    "name": "Year",
    "query": {
     "query": "SELECT DISTINCT \"Year\" FROM f1_laps ORDER BY \"Year\" DESC;"
    }
   },
   {
    "name": "Event",
    "query": {
     "query": "SELECT DISTINCT \"Event\" FROM f1_laps WHERE \"Year\" = ${Year} ORDER BY \"Event\" ASC;"
    }
   },
   {
    "name": "Driver",
    "query": {
     "query": "SELECT DISTINCT \"Driver\" FROM f1_laps WHERE \"Year\" = ${Year} AND \"Event\" = '${Event}';"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  MAX(\"LapNumber\") AS value\r\nFROM f1_laps\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  MAX(\"SpeedST\") AS value\r\nFROM f1_laps\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event'\r\n  AND \"SpeedST\" IS NOT NULL;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  MIN(EXTRACT(EPOCH FROM \"LapTime\")) AS value\r\nFROM f1_laps\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event'\r\n  AND \"LapTime\" IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Campeonato Mundial de Pilotos - $Year",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  \"Abbreviation\" AS \"Piloto\",\r\n  \"TeamName\" AS \"Escudería\",\r\n  SUM(\"Points\") AS \"Puntos Totales\"\r\nFROM f1_results\r\nWHERE \r\n  \"Year\" = $Year\r\nGROUP BY \"Abbreviation\", \"TeamName\"\r\nORDER BY \"Puntos Totales\" DESC;"
    }
   ]
  },
  {
   "title": "Velocidad Punta por Vuelta - $Event $Year",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  \"LapStartDate\" AS time,\r\n  \"Driver\" AS metric,\r\n  \"SpeedST\" AS value\r\nFROM f1_laps\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event'\r\n  AND \"Driver\" IN (${Driver:singlequote}) \r\n  AND \"SpeedST\" IS NOT NULL\r\nORDER BY \"LapStartDate\" ASC;"
    }
   ]
  },
  {
   "title": "Temperatura y Humedad - $Event $Year",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  (EXTRACT(EPOCH FROM \"Time\") / 60) AS minuto_sesion,\r\n  \"TrackTemp\" AS \"Temperatura Pista\",\r\n  \"AirTemp\" AS \"Temperatura Aire\",\r\n  \"Humidity\" AS \"Humedad (%)\"\r\nFROM f1_weather\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event'\r\nORDER BY \"Time\" ASC;"
    }
   ]
  },
  {
   "title": "Simulación - Tiempo de Vuelta por Compuesto",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\r\n  \"LapNumber\" AS \"Vuelta\",\r\n  \"Compound\" AS \"Compuesto\",\r\n  \"predicted_laptime\" AS \"Tiempo Predicho (s)\"\r\nFROM simulation_scenarios\r\nWHERE \r\n  \"Year\" = $Year\r\n  AND \"Event\" = '$Event'\r\n  AND \"Driver\" IN (${Driver:singlequote})\r\nORDER BY \"LapNumber\" ASC;"
    }
   ]
  }
 ]
}